package com.flutter.android;

public interface FlutterConstants {
    String CHANNEL_METHOD_PAGE = "CHANNEL_METHOD_PAGE";
    String CHANNEL_METHOD_NAVIGATION = "CHANNEL_METHOD_NAVIGATION";
    String NAVIGATION_BACK = "NAVIGATION_BACK";
    String NAVIGATION_CLOSE = "NAVIGATION_CLOSE";
    String CHANNEL_METHOD_BACK_STATUS = "CHANNEL_METHOD_BACK_STATUS";
}
