package com.flutter.android;

public interface FlutterConstants {
    //Flutter Channel methods.
    String CHANNEL_METHOD_PAGE = "CHANNEL_METHOD_PAGE";
    String CHANNEL_METHOD_NAVIGATION = "CHANNEL_METHOD_NAVIGATION";
    String NAVIGATION_CLOSE = "NAVIGATION_CLOSE";
    String NAVIGATION_BLOCK = "NAVIGATION_BLOCK";
    String NAVIGATION_BACK = "NAVIGATION_BACK";
    String CHANNEL_METHOD_BACK_STATUS = "CHANNEL_METHOD_BACK_STATUS";
    String CHANNEL_METHOD_CONFIG = "CHANNEL_METHOD_CONFIG";
    String CHANNEL_METHOD_EVENTS = "CHANNEL_METHOD_EVENTS";
    String CHANNEL_METHOD_DATA = "CHANNEL_METHOD_DATA";

    //Flutter Events.
    String EVENT_LOGOUT = "EVENT_LOGOUT";
    String EVENT_OPEN_URL = "EVENT_OPEN_URL";
    String EVENT_UPDATE_AVATAR = "EVENT_UPDATE_AVATAR";

    //FlutterView controls.
    String FLUTTER_SHOW = "FLUTTER_SHOW";
    String FLUTTER_HIDE = "FLUTTER_HIDE";
    String FLUTTER_SET_ACCESS_TOKEN = "FLUTTER_SET_ACCESS_TOKEN";

    //Flutter pages.
    String PAGE_DELETE_ACCOUNT = "PAGE_DELETE_ACCOUNT";
    String PAGE_DATA_COLLECTION = "PAGE_DATA_COLLECTION";
    String PAGE_USER_PROFILE = "PAGE_USER_PROFILE";
    String PAGE_POST_THREAD = "PAGE_POST_THREAD";
}